set_property SRC_FILE_INFO {cfile:{C:/Users/Julian/Documents/Work/CSE 100/Lab 1/HelloWorld/HelloWorld.srcs/constrs_1/imports/Downloads/Basys3_Master.xdc} rfile:../../../HelloWorld.srcs/constrs_1/imports/Downloads/Basys3_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {A}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports {B}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {C}]
